theme: jekyll-theme-minimal
title: Paul Boniol
description: PhD student at University of Paris
logo: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=zbHpNGUAAAAJ&citpid=14
show_downloads: false
